/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as DecksIndexRouteImport } from './routes/decks/index'
import { Route as PulseCreateRouteImport } from './routes/pulse/create'
import { Route as GamesJoinRouteImport } from './routes/games/join'
import { Route as GamesCreateRouteImport } from './routes/games/create'
import { Route as GamesRoomCodeResultsRouteImport } from './routes/games/$roomCode/results'
import { Route as GamesRoomCodePlayRouteImport } from './routes/games/$roomCode/play'
import { Route as GamesRoomCodeLobbyRouteImport } from './routes/games/$roomCode/lobby'
import { Route as DecksDeckIdViewRouteImport } from './routes/decks/$deckId/view'
import { Route as DecksDeckIdPresentRouteImport } from './routes/decks/$deckId/present'
import { Route as DecksDeckIdEditRouteImport } from './routes/decks/$deckId/edit'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseCreateRoute = PulseCreateRouteImport.update({
  id: '/pulse/create',
  path: '/pulse/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJoinRoute = GamesJoinRouteImport.update({
  id: '/games/join',
  path: '/games/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCreateRoute = GamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodeResultsRoute = GamesRoomCodeResultsRouteImport.update({
  id: '/games/$roomCode/results',
  path: '/games/$roomCode/results',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodePlayRoute = GamesRoomCodePlayRouteImport.update({
  id: '/games/$roomCode/play',
  path: '/games/$roomCode/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodeLobbyRoute = GamesRoomCodeLobbyRouteImport.update({
  id: '/games/$roomCode/lobby',
  path: '/games/$roomCode/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdViewRoute = DecksDeckIdViewRouteImport.update({
  id: '/decks/$deckId/view',
  path: '/decks/$deckId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdPresentRoute = DecksDeckIdPresentRouteImport.update({
  id: '/decks/$deckId/present',
  path: '/decks/$deckId/present',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdEditRoute = DecksDeckIdEditRouteImport.update({
  id: '/decks/$deckId/edit',
  path: '/decks/$deckId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/explore': typeof ExploreRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/pulse/create': typeof PulseCreateRoute
  '/decks/': typeof DecksIndexRoute
  '/games/': typeof GamesIndexRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/explore': typeof ExploreRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/pulse/create': typeof PulseCreateRoute
  '/decks': typeof DecksIndexRoute
  '/games': typeof GamesIndexRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/explore': typeof ExploreRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/pulse/create': typeof PulseCreateRoute
  '/decks/': typeof DecksIndexRoute
  '/games/': typeof GamesIndexRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/explore'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/pulse/create'
    | '/decks/'
    | '/games/'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/present'
    | '/decks/$deckId/view'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/explore'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/pulse/create'
    | '/decks'
    | '/games'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/present'
    | '/decks/$deckId/view'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/explore'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/pulse/create'
    | '/decks/'
    | '/games/'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/present'
    | '/decks/$deckId/view'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ExploreRoute: typeof ExploreRoute
  LandingPageRoute: typeof LandingPageRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  GamesCreateRoute: typeof GamesCreateRoute
  GamesJoinRoute: typeof GamesJoinRoute
  PulseCreateRoute: typeof PulseCreateRoute
  DecksIndexRoute: typeof DecksIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  DecksDeckIdEditRoute: typeof DecksDeckIdEditRoute
  DecksDeckIdPresentRoute: typeof DecksDeckIdPresentRoute
  DecksDeckIdViewRoute: typeof DecksDeckIdViewRoute
  GamesRoomCodeLobbyRoute: typeof GamesRoomCodeLobbyRoute
  GamesRoomCodePlayRoute: typeof GamesRoomCodePlayRoute
  GamesRoomCodeResultsRoute: typeof GamesRoomCodeResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse/create': {
      id: '/pulse/create'
      path: '/pulse/create'
      fullPath: '/pulse/create'
      preLoaderRoute: typeof PulseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/join': {
      id: '/games/join'
      path: '/games/join'
      fullPath: '/games/join'
      preLoaderRoute: typeof GamesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/create': {
      id: '/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof GamesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/results': {
      id: '/games/$roomCode/results'
      path: '/games/$roomCode/results'
      fullPath: '/games/$roomCode/results'
      preLoaderRoute: typeof GamesRoomCodeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/play': {
      id: '/games/$roomCode/play'
      path: '/games/$roomCode/play'
      fullPath: '/games/$roomCode/play'
      preLoaderRoute: typeof GamesRoomCodePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/lobby': {
      id: '/games/$roomCode/lobby'
      path: '/games/$roomCode/lobby'
      fullPath: '/games/$roomCode/lobby'
      preLoaderRoute: typeof GamesRoomCodeLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/view': {
      id: '/decks/$deckId/view'
      path: '/decks/$deckId/view'
      fullPath: '/decks/$deckId/view'
      preLoaderRoute: typeof DecksDeckIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/present': {
      id: '/decks/$deckId/present'
      path: '/decks/$deckId/present'
      fullPath: '/decks/$deckId/present'
      preLoaderRoute: typeof DecksDeckIdPresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/edit': {
      id: '/decks/$deckId/edit'
      path: '/decks/$deckId/edit'
      fullPath: '/decks/$deckId/edit'
      preLoaderRoute: typeof DecksDeckIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  DesignSystemRoute: DesignSystemRoute,
  ExploreRoute: ExploreRoute,
  LandingPageRoute: LandingPageRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  GamesCreateRoute: GamesCreateRoute,
  GamesJoinRoute: GamesJoinRoute,
  PulseCreateRoute: PulseCreateRoute,
  DecksIndexRoute: DecksIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  DecksDeckIdEditRoute: DecksDeckIdEditRoute,
  DecksDeckIdPresentRoute: DecksDeckIdPresentRoute,
  DecksDeckIdViewRoute: DecksDeckIdViewRoute,
  GamesRoomCodeLobbyRoute: GamesRoomCodeLobbyRoute,
  GamesRoomCodePlayRoute: GamesRoomCodePlayRoute,
  GamesRoomCodeResultsRoute: GamesRoomCodeResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
