/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesJoinRouteImport } from './routes/games/join'
import { Route as GamesCreateRouteImport } from './routes/games/create'
import { Route as GamesRoomCodeResultsRouteImport } from './routes/games/$roomCode/results'
import { Route as GamesRoomCodePlayRouteImport } from './routes/games/$roomCode/play'
import { Route as GamesRoomCodeLobbyRouteImport } from './routes/games/$roomCode/lobby'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJoinRoute = GamesJoinRouteImport.update({
  id: '/games/join',
  path: '/games/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCreateRoute = GamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodeResultsRoute = GamesRoomCodeResultsRouteImport.update({
  id: '/games/$roomCode/results',
  path: '/games/$roomCode/results',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodePlayRoute = GamesRoomCodePlayRouteImport.update({
  id: '/games/$roomCode/play',
  path: '/games/$roomCode/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodeLobbyRoute = GamesRoomCodeLobbyRouteImport.update({
  id: '/games/$roomCode/lobby',
  path: '/games/$roomCode/lobby',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/landing-page': typeof LandingPageRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/games/': typeof GamesIndexRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/landing-page': typeof LandingPageRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/games': typeof GamesIndexRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/landing-page': typeof LandingPageRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/games/': typeof GamesIndexRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/landing-page'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/games/'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/landing-page'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/games'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/landing-page'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/games/'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LandingPageRoute: typeof LandingPageRoute
  RegisterRoute: typeof RegisterRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  GamesCreateRoute: typeof GamesCreateRoute
  GamesJoinRoute: typeof GamesJoinRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GamesRoomCodeLobbyRoute: typeof GamesRoomCodeLobbyRoute
  GamesRoomCodePlayRoute: typeof GamesRoomCodePlayRoute
  GamesRoomCodeResultsRoute: typeof GamesRoomCodeResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/join': {
      id: '/games/join'
      path: '/games/join'
      fullPath: '/games/join'
      preLoaderRoute: typeof GamesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/create': {
      id: '/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof GamesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/results': {
      id: '/games/$roomCode/results'
      path: '/games/$roomCode/results'
      fullPath: '/games/$roomCode/results'
      preLoaderRoute: typeof GamesRoomCodeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/play': {
      id: '/games/$roomCode/play'
      path: '/games/$roomCode/play'
      fullPath: '/games/$roomCode/play'
      preLoaderRoute: typeof GamesRoomCodePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/lobby': {
      id: '/games/$roomCode/lobby'
      path: '/games/$roomCode/lobby'
      fullPath: '/games/$roomCode/lobby'
      preLoaderRoute: typeof GamesRoomCodeLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  DesignSystemRoute: DesignSystemRoute,
  LandingPageRoute: LandingPageRoute,
  RegisterRoute: RegisterRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  GamesCreateRoute: GamesCreateRoute,
  GamesJoinRoute: GamesJoinRoute,
  GamesIndexRoute: GamesIndexRoute,
  GamesRoomCodeLobbyRoute: GamesRoomCodeLobbyRoute,
  GamesRoomCodePlayRoute: GamesRoomCodePlayRoute,
  GamesRoomCodeResultsRoute: GamesRoomCodeResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
