export const colorPalette = [
  {
    label: "Red",
    tokens: [
      "--red-200",
      "--red-300",
      "--red-400",
      "--red-500",
      "--red-600",
      "--red-700",
      "--red-800",
      "--red-900",
    ],
  },
  {
    label: "Yellow",
    tokens: [
      "--yellow-200",
      "--yellow-300",
      "--yellow-400",
      "--yellow-500",
      "--yellow-600",
      "--yellow-700",
      "--yellow-800",
      "--yellow-900",
    ],
  },
  {
    label: "Green",
    tokens: [
      "--green-200",
      "--green-300",
      "--green-400",
      "--green-500",
      "--green-600",
      "--green-700",
      "--green-800",
      "--green-900",
    ],
  },
  {
    label: "Turqoise",
    tokens: [
      "--turqoise-200",
      "--turqoise-300",
      "--turqoise-400",
      "--turqoise-500",
      "--turqoise-600",
      "--turqoise-700",
      "--turqoise-800",
      "--turqoise-900",
    ],
  },

  {
    label: "Blue",
    tokens: [
      "--blue-200",
      "--blue-300",
      "--blue-400",
      "--blue-500",
      "--blue-600",
      "--blue-700",
      "--blue-800",
      "--blue-900",
    ],
  },
  {
    label: "Lavender",
    tokens: [
      "--lavender-200",
      "--lavender-300",
      "--lavender-400",
      "--lavender-500",
      "--lavender-600",
      "--lavender-700",
      "--lavender-800",
      "--lavender-900",
    ],
  },
  {
    label: "Fuchsia",
    tokens: [
      "--fuchsia-200",
      "--fuchsia-300",
      "--fuchsia-400",
      "--fuchsia-500",
      "--fuchsia-600",
      "--fuchsia-700",
      "--fuchsia-800",
      "--fuchsia-900",
    ],
  },
  {
    label: "Mulberry",
    tokens: [
      "--mulberry-200",
      "--mulberry-300",
      "--mulberry-400",
      "--mulberry-500",
      "--mulberry-600",
      "--mulberry-700",
      "--mulberry-800",
      "--mulberry-900",
    ],
  },
];

export const semanticTokens = [
  "--bg-canvas",
  "--bg-surface",
  "--bg-surface-raised",
  "--bg-subtle",
  "--bg-brand",
  "--text-primary",
  "--text-secondary",
  "--text-muted",
  "--text-on-brand",
  "--text-error",
  "--text-success",
  "--text-warning",
  "--text-info",
  "--border-default",
  "--border-subtle",
  "--border-focus",
  "--border-brand",
  "--action-hover",
  "--action-active",
  "--action-disabled",
  "--status-success",
  "--status-warning",
  "--status-error",
  "--status-info",
];
