import type { ScoreBoardProps } from "../../components/Games/ScoreBoard/ScoreBoard";

export interface ThemePreset {
  label: string;
  huePrimary: number;
  hueAccent: number;
}

export const themePresets: ThemePreset[] = [
  { label: "Brand", huePrimary: 290, hueAccent: 50 },
  { label: "Indigo", huePrimary: 260, hueAccent: 25 },
  { label: "Forest", huePrimary: 160, hueAccent: 35 },
  { label: "Sunset", huePrimary: 30, hueAccent: 280 },
  { label: "Ocean", huePrimary: 210, hueAccent: 60 },
  { label: "Orchid", huePrimary: 300, hueAccent: 45 },
  { label: "Midnight", huePrimary: 240, hueAccent: 180 },
];

export const questionCardData = {
  round: 8,
  totalRounds: 10,
  timeRemaining: 25,
  question: {
    id: "q-lotr-108",
    questionText: "In which fiery chasm was the One Ring finally destroyed?",
    options: [
      "The Mines of Maria",
      "The Cracks of Doom",
      "The Pits of Isengard",
      "The Black Gate",
    ],
    pointValue: 500,
    timeLimit: 30,
    type: "multiple-choice",
    imageUrl: "https://example.com/images/mount-doom.jpg",
  },
};

export const gameOverData = {
  currentUserId: "user-001",
  placements: [
    {
      userId: "user-003",
      userName: "Gandalf the Grey",
      finalScore: 9500,
      placement: 1,
      correctAnswers: 10,
      totalQuestions: 10,
      guest: false,
    },
    {
      userId: "user-004",
      userName: "Aragorn",
      finalScore: 1250,
      placement: 2,
      correctAnswers: 9,
      totalQuestions: 10,
      guest: false,
    },
    {
      userId: "user-005",
      userName: "Legolas Greenleaf",
      finalScore: 1150,
      placement: 3,
      correctAnswers: 8,
      totalQuestions: 10,
      guest: false,
    },
    {
      userId: "user-006",
      userName: "Gimli Son of Gloin",
      finalScore: 1149,
      placement: 4,
      correctAnswers: 8,
      totalQuestions: 10,
      guest: false,
    },
    {
      userId: "user-002",
      userName: "Samwise Gamgee",
      finalScore: 900,
      placement: 5,
      correctAnswers: 7,
      totalQuestions: 10,
      guest: false,
    },
    {
      userId: "user-001",
      userName: "Frodo Baggins",
      finalScore: 850,
      placement: 6,
      correctAnswers: 6,
      totalQuestions: 10,
      guest: false,
    },
    {
      userId: "guest-999",
      userName: "Strider",
      finalScore: 320,
      placement: 7,
      correctAnswers: 3,
      totalQuestions: 10,
      guest: true,
    },
    {
      userId: "guest-888",
      userName: "Peregrin Took",
      finalScore: 150,
      placement: 8,
      correctAnswers: 1,
      totalQuestions: 10,
      guest: true,
    },
  ],
};
export const colorPalette = [
  {
    label: "Brand",
    tokens: [
      "--electric-violet-200",
      "--electric-violet-500",
      "--electric-violet",
      "--electric-violet-700",
      "--electric-violet-900",
      "--blaze-orange-100",
      "--blaze-orange",
      "--blaze-orange-900",
      "--mariana-blue-100",
      "--mariana-blue",
      "--tolopea",
      "--aquamarine-100",
      "--aquamarine",
      "--aquamarine-900",
      "--shell",
      "--black-white",
      "--black-russian",
    ],
  },
  {
    label: "Red",
    tokens: [
      "--red-200",
      "--red-300",
      "--red-400",
      "--red-500",
      "--red-600",
      "--red-700",
      "--red-800",
      "--red-900",
    ],
  },
  {
    label: "Yellow",
    tokens: [
      "--yellow-200",
      "--yellow-300",
      "--yellow-400",
      "--yellow-500",
      "--yellow-600",
      "--yellow-700",
      "--yellow-800",
      "--yellow-900",
    ],
  },
  {
    label: "Green",
    tokens: [
      "--green-200",
      "--green-300",
      "--green-400",
      "--green-500",
      "--green-600",
      "--green-700",
      "--green-800",
      "--green-900",
    ],
  },
  {
    label: "Turqoise",
    tokens: [
      "--turqoise-200",
      "--turqoise-300",
      "--turqoise-400",
      "--turqoise-500",
      "--turqoise-600",
      "--turqoise-700",
      "--turqoise-800",
      "--turqoise-900",
    ],
  },

  {
    label: "Blue",
    tokens: [
      "--blue-200",
      "--blue-300",
      "--blue-400",
      "--blue-500",
      "--blue-600",
      "--blue-700",
      "--blue-800",
      "--blue-900",
    ],
  },
  {
    label: "Lavender",
    tokens: [
      "--lavender-200",
      "--lavender-300",
      "--lavender-400",
      "--lavender-500",
      "--lavender-600",
      "--lavender-700",
      "--lavender-800",
      "--lavender-900",
    ],
  },
  {
    label: "Fuchsia",
    tokens: [
      "--fuchsia-200",
      "--fuchsia-300",
      "--fuchsia-400",
      "--fuchsia-500",
      "--fuchsia-600",
      "--fuchsia-700",
      "--fuchsia-800",
      "--fuchsia-900",
    ],
  },
  {
    label: "Mulberry",
    tokens: [
      "--mulberry-200",
      "--mulberry-300",
      "--mulberry-400",
      "--mulberry-500",
      "--mulberry-600",
      "--mulberry-700",
      "--mulberry-800",
      "--mulberry-900",
    ],
  },
];

export const semanticTokens = [
  "--bg-canvas",
  "--bg-surface",
  "--bg-surface-raised",
  "--bg-subtle",
  "--bg-brand",
  "--text-primary",
  "--text-secondary",
  "--text-muted",
  "--text-on-brand",
  "--text-error",
  "--text-success",
  "--text-warning",
  "--text-info",
  "--border-default",
  "--border-subtle",
  "--border-focus",
  "--border-brand",
  "--action-hover",
  "--action-active",
  "--action-disabled",
  "--status-success",
  "--status-warning",
  "--status-error",
  "--status-info",
];

export const playersData: ScoreBoardProps = {
  players: [
    {
      userId: "user-001",
      userName: "Frodo Baggins",
      pictureUrl: "https://example.com/avatars/frodo.jpg",
      isGuest: false,
      score: 450,
    },
    {
      userId: "user-002",
      userName: "Samwise Gamgee",
      pictureUrl: "https://example.com/avatars/sam.jpg",
      isGuest: false,
      score: 500,
    },
    {
      userId: "user-003",
      userName: "Gandalf the Grey",
      pictureUrl: "https://example.com/avatars/gandalf.jpg",
      isGuest: false,
      score: 9001,
    },
    {
      userId: "user-004",
      userName: "Aragorn",
      pictureUrl: "https://example.com/avatars/aragorn.jpg",
      isGuest: false,
      score: 850,
    },
    {
      userId: "user-005",
      userName: "Legolas Greenleaf",
      pictureUrl: "https://example.com/avatars/legolas.jpg",
      isGuest: false,
      score: 770,
    },
    {
      userId: "user-006",
      userName: "Gimli Son of Gloin",
      pictureUrl: "https://example.com/avatars/gimli.jpg",
      isGuest: false,
      score: 769,
    },
    {
      userId: "guest-999",
      userName: "Strider",
      pictureUrl: "",
      isGuest: true,
      score: 120,
    },
    {
      userId: "guest-888",
      userName: "Peregrin Took",
      pictureUrl: "https://example.com/avatars/pippin.jpg",
      isGuest: true,
      score: 50,
    },
  ],
  currentUserId: "user-001",
};

export const formSampleData = {
  radioOptions: [
    { label: "Classic", value: "classic" },
    { label: "Timed", value: "timed" },
    { label: "Survival", value: "survival" },
  ],
};

export const RoundResultData = {
  round: 3,
  correctAnswer: 9,
  correctAnswerText: "The Nine Walkers",
  playerResults: [
    {
      userId: "user-003",
      userName: "Gandalf the Grey",
      selectedOption: 9,
      wasCorrect: true,
      pointsAwarded: 100,
      totalScore: 9101,
    },
    {
      userId: "user-002",
      userName: "Samwise Gamgee",
      selectedOption: 9,
      wasCorrect: true,
      pointsAwarded: 100,
      totalScore: 600,
    },
    {
      userId: "user-005",
      userName: "Legolas Greenleaf",
      selectedOption: 9,
      wasCorrect: true,
      pointsAwarded: 100,
      totalScore: 870,
    },
    {
      userId: "user-006",
      userName: "Gimli Son of Gloin",
      selectedOption: 9,
      wasCorrect: true,
      pointsAwarded: 100,
      totalScore: 869,
    },
    {
      userId: "user-001",
      userName: "Frodo Baggins",
      selectedOption: 9,
      wasCorrect: true,
      pointsAwarded: 100,
      totalScore: 550,
    },
    {
      userId: "user-004",
      userName: "Aragorn",
      selectedOption: 9,
      wasCorrect: true,
      pointsAwarded: 100,
      totalScore: 950,
    },
    {
      userId: "guest-888",
      userName: "Peregrin Took",
      selectedOption: 2,
      wasCorrect: false,
      pointsAwarded: 0,
      totalScore: 50,
    },
    {
      userId: "guest-999",
      userName: "Strider",
      selectedOption: 1,
      wasCorrect: false,
      pointsAwarded: 0,
      totalScore: 120,
    },
  ],
};
