spring.application.name=brainflex


# Tell Spring to load the .env file as a configuration source
spring.config.import=optional:file:../.env[.properties]



# Disable strict check for MongoDB and Redis on startup
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

spring.docker.compose.enabled=false

logging.level.org.springframework.security=DEBUG


# Now map the environment variables to the OAuth settings
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}